CREATE TABLE project
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255)                            NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    manager_id BIGINT,
    CONSTRAINT project_pkey PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT client_pkey PRIMARY KEY (id)
);

ALTER TABLE project
    ADD CONSTRAINT project_user_id_fk FOREIGN KEY (manager_id) REFERENCES "user" (id) ON UPDATE NO ACTION ON DELETE NO ACTION;